### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by Tuqz** [Tuqz/athelia#1]
The 'block' techdemo fails to respond to user input.

**Comment by jacob-hartmann** [comment]
I can confirmed this on Windows 7. I am working on getting debug symbols built in an attempt to track this down.

**Comment by Jacob843** [comment]
Tuqz, I just noticed that both techdemos/block/main.cpp and techdemos/template/main.cpp have main() functions. One calls OIS while one doesn't. On my system, scons seems to be compiling template's main (the log name is "LOG_NAME", which matches up locally), when it should be compiling block's main. This should be fixed. Additionally, note that I have created the nightly branch, where I will be pushing most of my changes.

**Comment by jacob-hartmann** [comment]
OIS works in Nightly build 5f76d5e  If you want Tuqz, you can close this.

**Comment by jacob-hartmann** [comment]
Since there has been no response to this issue within a few days, and it is confirmed fixed in the Nightly, I am closing this issue.
